apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
spec:
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:1.26
        env:
          - name: JAEGER_AGENT_HOST
            value: jaeger-prod-collector-headless
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
spec:
  selector:
    app: hotrod
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotrod-ingress
  labels:
    name: hotrod-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hotrod.hbinsight.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hotrod
            port: 
              number: 8080




