apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oauth
  data:

  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    remoteRef:
      key: grafana-oauth
      property: client_Id

  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      key: grafana-oauth
      property: client_secert


  # # metadataPolicy to fetch all the labels in JSON format
  # - secretKey: tags
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: foo

  # # metadataPolicy to fetch a specific label (dev) from the source secret
  # - secretKey: developer
  #   remoteRef:
  #     metadataPolicy: Fetch
  #     key: foo
  #     property: dev