site_name: Perfect Kubernetes Cluster (PKC)
docs_dir: src
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.tabs

    # - toc.follow
    # - toc.integrate 
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: README.md
  - Getting started: 
    - getting-started.md
    - kind: kind/README.md
    - Prometheus Operator: observability/prom-operator/README.md
    - Cilium: cilium/README.md
    - Ingress: ingress/README.md
