# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/dotexec/workspace/k8s/kind/roots.pem
      containerPath: /etc/ssl/certs/roots.pem
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: 127.0.0.1
    protocol: TCP
- role: worker
  extraMounts:
    - hostPath: /home/dotexec/workspace/k8s/kind/roots.pem
      containerPath: /etc/ssl/certs/roots.pem
- role: worker
  extraMounts:
    - hostPath: /home/dotexec/workspace/k8s/kind/roots.pem
      containerPath: /etc/ssl/certs/roots.pem
- role: worker
  extraMounts:
    - hostPath: /home/dotexec/workspace/k8s/kind/roots.pem
      containerPath: /etc/ssl/certs/roots.pem
networking:
  disableDefaultCNI: true
  kubeProxyMode: none 
  podSubnet: "10.10.0.0/16"
  serviceSubnet: "10.11.0.0/16"