apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFthbGVydG5hbWVdCiAgcmVjZWl2ZXI6IGVtYWlsX2FuZF9zbGFjawpyZWNlaXZlcnM6Ci0gbmFtZTogZW1haWxfYW5kX3NsYWNrCiAgZW1haWxfY29uZmlnczoKICAtIHRvOiA8dGhlIGVtYWlsIGFkZHJlc3MgdG8gc2VuZCBub3RpZmljYXRpb25zIHRvPgogICAgZnJvbTogPHRoZSBzZW5kZXIgYWRkcmVzcz4KICAgIHNtYXJ0aG9zdDogPHRoZSBTTVRQIGhvc3QgdGhyb3VnaCB3aGljaCBlbWFpbHMgYXJlIHNlbnQ+CiAgICAjIFNNVFAgYXV0aGVudGljYXRpb24gaW5mb3JtYXRpb24uCiAgICBhdXRoX3VzZXJuYW1lOiA8dGhlIHVzZXJuYW1lPgogICAgYXV0aF9pZGVudGl0eTogPHRoZSBpZGVudGl0eT4KICAgIGF1dGhfcGFzc3dvcmQ6IDx0aGUgcGFzc3dvcmQ+CiAgICBoZWFkZXJzOgogICAgICBzdWJqZWN0OiAnTG9uZ2hvcm4tQWxlcnQnCiAgICB0ZXh0OiB8LQogICAgICB7eyByYW5nZSAuQWxlcnRzIH19CiAgICAgICAgKkFsZXJ0Oioge3sgLkFubm90YXRpb25zLnN1bW1hcnkgfX0gLSBge3sgLkxhYmVscy5zZXZlcml0eSB9fWAKICAgICAgICAqRGVzY3JpcHRpb246KiB7eyAuQW5ub3RhdGlvbnMuZGVzY3JpcHRpb24gfX0KICAgICAgICAqRGV0YWlsczoqCiAgICAgICAge3sgcmFuZ2UgLkxhYmVscy5Tb3J0ZWRQYWlycyB9fSDigKIgKnt7IC5OYW1lIH19OiogYHt7IC5WYWx1ZSB9fWAKICAgICAgICB7eyBlbmQgfX0KICAgICAge3sgZW5kIH19CiAgc2xhY2tfY29uZmlnczoKICAtIGFwaV91cmw6IDx0aGUgU2xhY2sgd2ViaG9vayBVUkw+CiAgICBjaGFubmVsOiA8dGhlIGNoYW5uZWwgb3IgdXNlciB0byBzZW5kIG5vdGlmaWNhdGlvbnMgdG8+CiAgICB0ZXh0OiB8LQogICAgICB7eyByYW5nZSAuQWxlcnRzIH19CiAgICAgICAgKkFsZXJ0Oioge3sgLkFubm90YXRpb25zLnN1bW1hcnkgfX0gLSBge3sgLkxhYmVscy5zZXZlcml0eSB9fWAKICAgICAgICAqRGVzY3JpcHRpb246KiB7eyAuQW5ub3RhdGlvbnMuZGVzY3JpcHRpb24gfX0KICAgICAgICAqRGV0YWlsczoqCiAgICAgICAge3sgcmFuZ2UgLkxhYmVscy5Tb3J0ZWRQYWlycyB9fSDigKIgKnt7IC5OYW1lIH19OiogYHt7IC5WYWx1ZSB9fWAKICAgICAgICB7eyBlbmQgfX0KICAgICAge3sgZW5kIH19
kind: Secret
metadata:
  name: alertmanager-longhorn
---

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: longhorn
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-longhorn
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: longhorn