apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: edgeprime.intra  # The bundle name will also be used for the target
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet, such as
  # those issued by Let's Encrypt, Google, Amazon and others.
  - useDefaultCAs: false

  - inLine: |
      -----BEGIN CERTIFICATE-----
      MIIBujCCAWGgAwIBAgIQAuVtmBw26DLgW+P6qRs/qjAKBggqhkjOPQQDAjA8MRgw
      FgYDVQQKEw9lZGdlcHJpbWUuaW50cmExIDAeBgNVBAMTF2VkZ2VwcmltZS5pbnRy
      YSBSb290IENBMB4XDTIzMDgzMDE2MDMyMFoXDTMzMDgyNzE2MDMyMFowPDEYMBYG
      A1UEChMPZWRnZXByaW1lLmludHJhMSAwHgYDVQQDExdlZGdlcHJpbWUuaW50cmEg
      Um9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPy+xtsx1IZSIHWeaPVH
      8C+SzEIfl4cqdHHcKyU0olsTu3Dzj0mwjs4M8QYsiR7u7GW36wzO0UzdXuTWZ6Cn
      6OGjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1Ud
      DgQWBBRvkmt2PH4c1gZ06heIs0gPpGaxsDAKBggqhkjOPQQDAgNHADBEAiADo9yr
      L7LTC1aLVeO8G2ZEj7ujo0jX1x8uinNSds0IMQIgFnEe28WywHsyCTa+yiTStUiX
      XnjLeNlJzOt8dlZPW04=
      -----END CERTIFICATE-----

  target:
    # Sync the bundle to a ConfigMap called `my-org.com` in every namespace which
    # has the label "linkerd.io/inject=enabled"
    # All ConfigMaps will include a PEM-formatted bundle, here named "root-certs.pem"
    # and in this case we also request binary formatted bundles in JKS and PKCS#12 formats,
    # here named "bundle.jks" and "bundle.p12".
    configMap:
      key: "root-certs.crt"